trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  projectPath: 'OneDrive/Desktop/Quiz4/ibra_quiz4_dotnet/ibra_quiz4_dotnet.csproj'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore "$(Build.SourcesDirectory)\$(projectPath)"
  displayName: 'Restore packages'

- script: dotnet build "$(Build.SourcesDirectory)\$(projectPath)" --configuration $(buildConfiguration)
  displayName: 'Build project'

- script: dotnet publish "$(Build.SourcesDirectory)\$(projectPath)" -c $(buildConfiguration) -o "$(Build.ArtifactStagingDirectory)"
  displayName: 'Publish project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'